version: '3.4'

services:
  pearlbookstore.api:
    image: ${DOCKER_REGISTRY-}pearlbookstoreapi
    build:
      context: .
      dockerfile: PearlBookstore.API/Dockerfile
    ports:
      - "10110:8080"
      - "10111:8081" 
    depends_on:
      db:
        condition: service_started
  db: 
    image: mysql
    command: ["mysqld", "--mysql-native-password=ON"]
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password123
    ports:
      - '3307:3306'
    volumes:
     - mysql_data:/var/lib/mysql
  pearlbookstore.web:
    image: ${DOCKER_REGISTRY-}pearlbookstoreweb
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    build:
      context: .
      dockerfile: PearlBookstore.WEB/PearlBookstore.WEB/Dockerfile
    ports:
      - "20220:8080"
      - "20221:8081" 
    depends_on:
      pearlbookstore.api:
        condition: service_started
      db:
        condition: service_started
volumes:
  mysql_data:
  

